sonar.projectKey=RealEstateManagement
sonar.projectName=Real Estate Management
sonar.host.url=http://localhost:9000
sonar.login=sqp_750d7d92e5be7769a2e1ad57ca19fd2cffc49525

sonar.sourceEncoding=UTF-8

sonar.sources=realestatemanagementfrontend,RealEstateManagementProject

sonar.exclusions=**/node_modules/**, **/dist/**, **/*.spec.ts


sonar.cs.opencover.reportsPaths=RealEstateManagementProject/TestResults/**/*.xml
sonar.exclusions=**/Migrations/**/*

